import { Experience } from '@/app/types'

export default [
  {
    id: 5,
    company: 'Artificial Labs',
    industry: 'insurtech',
    role: 'Frontend Engineer',
    start: { month: 3, year: 2022 },
    end: { month: 3, year: 2025 },
    location: 'London, UK',
    stack: ['React', 'TypeScript', 'TailwindCSS v3', 'AWS'],
    link: 'https://artificial.io',
    responsibilities: [
      'Led frontend development of a new insurance underwriting platform, transforming an initial prototype into a production-grade React/TypeScript application following MRCv3 standards.',
      'Solely responsible for application architecture, including critical refactoring from Create React App (CRA) to Vite to significantly improve build performance.',
      'Introduced and established E2E testing with Cypress, ensuring platform stability and accelerating development workflows.',
      'Actively contributed to product strategy, offering technical input during design sessions and resolving architectural challenges during project planning.',
      'Extended collaboration beyond development by participating in UI/UX design refinement, improving design specification quality in Figma workflows.',
      'Played a key role in scaling the frontend team and product maturity, helping secure multiple high-value contracts with UK insurers and preparing the platform for entry into the US market.',
      'Advocated for adoption of best practices, modern tooling, and consistent code quality across the frontend team.',
    ],
  },
  {
    id: 4,
    company: 'Chronos',
    industry: 'wfm',
    role: 'Product Engineer',
    start: { month: 11, year: 2021 },
    end: { month: 6, year: 2023 },
    location: 'PL',
    stack: ['React', 'TypeScript', 'MUI', 'Google Cloud Platform', 'Node.js'],
    responsibilities: [
      'Led the design, development, and maintenance of multiple React-based applications, including workforce management dashboards and tablet-based QR code scanning solutions.',
      'Designed complete UX/UI workflows, including the main platform, internal apps, and the marketing landing page, ensuring a seamless user experience across devices.',
      'Collaborated directly with clients to gather feedback, define requirements, propose solutions, and deliver new features aligned with business needs.',
      'Managed iterative product improvements, handling feature rollouts, user acceptance testing (UAT), and ensuring high adoption rates.',
      'Contributed to system architecture design and implementation using React, TypeScript, Node.js, and Google Cloud Platform services.',
    ],
  },
  {
    id: 3,
    company: 'Currency One',
    industry: 'fintech',
    role: 'Software Engineer',
    start: { month: 3, year: 2020 },
    end: { month: 11, year: 2021 },
    location: 'Poznan, PL',
    stack: [
      'React',
      'TypeScript',
      'Angular 1',
      'microservices',
      'Python',
      'Kotlin',
      'Node.js',
      'Redux',
      'SASS',
      'Bootstrap',
      'MySQL',
      'MongoDB',
      'Postgres',
    ],
    link: 'https://currency-one.com/',
    responsibilities: [
      'Developed and maintained a range of CQRS-based microservices for a high-volume currency exchange platform, primarily using Node.js, with additional contributions in Python and Kotlin.',
      'Built internal NPM libraries and developed new microservices, ensuring scalability, resilience, and alignment with business needs.',
      'Contributed to frontend development by maintaining and extending the Backoffice suite (AngularJS) and InternetowyKantor.pl (React).',
      'Led the initiative to integrate React into existing micro-frontend architecture within internal management applications.',
      'Handled production incident resolution, actively monitoring services via Kibana and managing message reprocessing through RabbitMQ.',
      'Actively participated in Agile/Scrum ceremonies, collaborating with cross-functional teams to deliver high-quality solutions.',
      'Quickly gained a reputation as a "problem solver," resolving technical issues efficiently and reliably across the stack.',
    ],
  },
  {
    id: 2,
    company: '4LS/Genetix',
    industry: 'logistics',
    role: 'Fullstack Developer',
    start: { month: 9, year: 2018 },
    end: { month: 3, year: 2020 },
    location: 'Poznan, PL',
    stack: [
      'React',
      'TypeScript',
      'microservices',
      'Node.js',
      'SQLServer',
      'ETL',
      'Postgres',
    ],
    link: 'https://4ls.pl',
    responsibilities: [
      'Designed and developed a suite of web applications for real-time and historical tracking of courier deliveries, integrating GPS data from Microsoft SQL Server.',
      'Built and maintained the entire frontend in React, while independently implementing backend services using Node.js, REST, GraphQL, and PostgreSQL.',
      'Developed ETL processes to synchronize and migrate logistics data from on-premises Microsoft servers to cloud-based PostgreSQL databases.',
      'Quickly transitioned from frontend-focused development to fullstack responsibilities to meet project demands, self-learning backend technologies under tight deadlines.',
      'Collaborated directly with operational teams to ensure the system met dynamic business requirements and improved delivery route visibility.',
    ],
  },
  {
    id: 1,
    company: 'Beiersdorf',
    industry: 'cosmetics',
    role: 'Data Analyst',
    start: { month: 7, year: 2017 },
    end: { month: 8, year: 2018 },
    location: 'Poznan, PL',
    stack: ['MSAccess', 'SQL', 'VBA'],
    link: 'https://www.niveapolska.pl/',
    responsibilities: [
      'Built a comprehensive technical database cataloging all product components (caps, jars, labels, packaging) to support manufacturing and production planning.',
      'Designed and maintained the database in MS Access, ensuring it was easily accessible and scalable for engineering teams.',
      'Suppoerted regular expansion of the database to include tooling parts essential for different product lines.',
      'Collaborated closely with manufacturing engineers, providing analytical support for production optimization.',
    ],
  },
] satisfies Experience[]
